
-----------------------------------------------------CREATING STAGING LAYER------------------------------------------------------
--------------------------------------------------------CUSTOMER STAGING-------------------------------------------------------------
/*DROP TABLE [Staging].[S_CDW_SAPP_CUSTOMER]
SELECT * FROM [Staging].[S_CDW_SAPP_CUSTOMER]
SELECT * FROM [Landing].[U_CDW_SAPP_D_CUSTOMER]*/

	DROP TABLE IF EXISTS [Staging].[S_CDW_SAPP_CUSTOMER]
	SELECT * INTO [Staging].[S_CDW_SAPP_CUSTOMER]
	FROM [Landing].[U_CDW_SAPP_D_CUSTOMER]  WHERE 1=2;

	MERGE INTO [Staging].[S_CDW_SAPP_CUSTOMER] TRG
	USING [Landing].[U_CDW_SAPP_D_CUSTOMER]  SRC ON 
	TRG.CUST_ID = SRC.CUST_ID

	WHEN NOT MATCHED 
	THEN INSERT (CUST_ID, CUST_F_NAME, CUST_M_NAME, CUST_L_NAME, CUST_SSN, CUST_STREET, CUST_CITY,CUST_STATE, CUST_COUNTRY,
	[CUST_ZIP], CUST_PHONE, [CUST_EMAIL ], LOADING_DATE, SOURCE_DATA)
	VALUES (SRC.CUST_ID, SRC.CUST_F_NAME, SRC.CUST_M_NAME, SRC.CUST_L_NAME, SRC.CUST_SSN, SRC.CUST_STREET, SRC.CUST_CITY,
	SRC.CUST_STATE, SRC.CUST_COUNTRY, SRC.[CUST_ZIP], SRC.CUST_PHONE, SRC.[CUST_EMAIL ], SRC.LOADING_DATE, SRC.SOURCE_DATA)

	WHEN MATCHED AND(
	TRG.CUST_ID != SRC.CUST_ID OR 
	TRG.CUST_F_NAME != SRC.CUST_F_NAME OR
	TRG.CUST_M_NAME != SRC.CUST_M_NAME OR 
	TRG.CUST_L_NAME != SRC.CUST_L_NAME OR 
	TRG.CUST_SSN != SRC.CUST_SSN OR 
	TRG.CUST_STREET!= SRC.CUST_STREET OR
	TRG.CUST_CITY != SRC.CUST_CITY OR 
	TRG.CUST_STATE != SRC.CUST_STATE OR 
	TRG.CUST_COUNTRY != SRC.CUST_COUNTRY OR
	TRG.[CUST_ZIP] != SRC.[CUST_ZIP] OR
	TRG.CUST_PHONE != SRC.CUST_PHONE OR
	TRG.[CUST_EMAIL ] != SRC.[CUST_EMAIL ] OR
	TRG.LOADING_DATE != SRC.LOADING_DATE OR
	TRG.SOURCE_DATA != SRC.SOURCE_DATA)
	THEN UPDATE SET 
	TRG.CUST_ID = SRC.CUST_ID, 
	TRG.CUST_F_NAME = SRC.CUST_F_NAME, 
	TRG.CUST_M_NAME = SRC.CUST_M_NAME,  
	TRG.CUST_L_NAME = SRC.CUST_L_NAME,  
	TRG.CUST_SSN = SRC.CUST_SSN,  
	TRG.CUST_STREET= SRC.CUST_STREET, 
	TRG.CUST_CITY = SRC.CUST_CITY, 
	TRG.CUST_STATE = SRC.CUST_STATE, 
	TRG.CUST_COUNTRY = SRC.CUST_COUNTRY, 
	TRG.[CUST_ZIP] = SRC.[CUST_ZIP], 
	TRG.CUST_PHONE = SRC.CUST_PHONE, 
	TRG.[CUST_EMAIL ] = SRC.[CUST_EMAIL ], 
	TRG.LOADING_DATE = SRC.LOADING_DATE, 
	TRG.SOURCE_DATA = SRC.SOURCE_DATA;

------------------------------------------------------SUPPLIER STAGING------------------------------------------------------------
/*DROP TABLE [Staging].[S_CDW_SAPP_SUPPLIER]
SELECT * FROM [Staging].[S_CDW_SAPP_SUPPLIER]*/

	DROP TABLE IF EXISTS [Staging].[S_CDW_SAPP_SUPPLIER]
	SELECT * INTO [Staging].[S_CDW_SAPP_SUPPLIER]
	FROM [Landing].[U_CDW_SAPP_D_SUPPLIER] WHERE 1=2;

	MERGE INTO [Staging].[S_CDW_SAPP_SUPPLIER] TRG
	USING [Landing].[U_CDW_SAPP_D_SUPPLIER] SRC ON 
	TRG.SUPPLIER_ID = SRC.SUPPLIER_ID

	WHEN NOT MATCHED 
	THEN INSERT (SUPPLIER_ID, SUPPLIER_NAME, SUPPLIER_SSN, SUPPLIER_PHONE, SUPPLIER_LOC, LOADING_DATE, SOURCE_DATA)
	VALUES (SRC.SUPPLIER_ID,SRC.SUPPLIER_NAME, SRC.SUPPLIER_SSN, SRC.SUPPLIER_PHONE, SRC.SUPPLIER_LOC,
	SRC.LOADING_DATE, SRC.SOURCE_DATA)

	WHEN MATCHED AND(
	TRG.SUPPLIER_ID != SRC.SUPPLIER_ID OR 
	TRG.SUPPLIER_NAME != SRC.SUPPLIER_NAME OR 
	TRG.SUPPLIER_SSN != SRC.SUPPLIER_SSN OR
	TRG.SUPPLIER_PHONE != SRC.SUPPLIER_PHONE OR 
	TRG.SUPPLIER_LOC != SRC.SUPPLIER_LOC OR
	TRG.LOADING_DATE != SRC.LOADING_DATE OR
	TRG.SOURCE_DATA != SRC.SOURCE_DATA)
	THEN UPDATE SET 
	TRG.SUPPLIER_ID = SRC.SUPPLIER_ID,
	TRG.SUPPLIER_NAME = SRC.SUPPLIER_NAME,  
	TRG.SUPPLIER_SSN = SRC.SUPPLIER_SSN, 
	TRG.SUPPLIER_PHONE = SRC.SUPPLIER_PHONE,  
	TRG.SUPPLIER_LOC = SRC.SUPPLIER_LOC,
	TRG.LOADING_DATE = SRC.LOADING_DATE, 
	TRG.SOURCE_DATA = SRC.SOURCE_DATA;

-------------------------------------------------------BRANCH STAGING------------------------------------------------------------------------
/*DROP TABLE [Staging].[S_CDW_SAPP_BRANCH]
SELECT * FROM [Staging].[S_CDW_SAPP_BRANCH]
exec sp_help '[Staging].[S_CDW_SAPP_BRANCH]';*/

	DROP TABLE IF EXISTS [Staging].[S_CDW_SAPP_BRANCH]
	SELECT * INTO [Staging].[S_CDW_SAPP_BRANCH]
		FROM [Landing].[U_CDW_SAPP_D_BRANCH] WHERE 1=2;

	MERGE INTO [Staging].[S_CDW_SAPP_BRANCH] TRG
	USING [Landing].[U_CDW_SAPP_D_BRANCH] SRC ON 
	TRG.BRANCH_CODE = SRC.BRANCH_CODE

	WHEN NOT MATCHED 
	THEN INSERT (BRANCH_CODE, BRANCH_NAME, BRANCH_STREET, BRANCH_CITY, BRANCH_STATE, 
	BRANCH_ZIP, BRANCH_PHONE, LOADING_DATE, SOURCE_DATA)
	VALUES (SRC.BRANCH_CODE, SRC.BRANCH_NAME, SRC.BRANCH_STREET, SRC.BRANCH_CITY, 
	SRC.BRANCH_STATE, SRC.BRANCH_ZIP, SRC.BRANCH_PHONE, SRC.LOADING_DATE, SRC.SOURCE_DATA)

	WHEN MATCHED AND(
	TRG.BRANCH_CODE != SRC.BRANCH_CODE OR 
	TRG.BRANCH_NAME != SRC.BRANCH_NAME OR
	TRG.BRANCH_STREET != SRC.BRANCH_STREET OR 
	TRG.BRANCH_STATE != SRC.BRANCH_STATE OR 
	TRG.BRANCH_ZIP != SRC.BRANCH_ZIP OR 
	TRG.BRANCH_PHONE!= SRC.BRANCH_PHONE OR
	TRG.LOADING_DATE != SRC.LOADING_DATE OR 
	TRG.SOURCE_DATA != SRC.SOURCE_DATA)
	THEN UPDATE SET 
	TRG.BRANCH_CODE = SRC.BRANCH_CODE, 
	TRG.BRANCH_NAME = SRC.BRANCH_NAME, 
	TRG.BRANCH_STREET = SRC.BRANCH_STREET,  
	TRG.BRANCH_STATE = SRC.BRANCH_STATE,  
	TRG.BRANCH_ZIP = SRC.BRANCH_ZIP,  
	TRG.BRANCH_PHONE = SRC.BRANCH_PHONE, 
	TRG.LOADING_DATE = SRC.LOADING_DATE,  
	TRG.SOURCE_DATA = SRC.SOURCE_DATA;

--------------------------------------------------------TIME STAGING------------------------------------------------------------------------------
/*SELECT * FROM [Landing].[U_CDW_SAPP_D_TIME]
SELECT * FROM [Staging].[S_CDW_SAPP_D_TIME]
DROP TABLE [Staging].[S_CDW_SAPP_D_TIME]*/

	DROP TABLE IF EXISTS [Staging].[S_CDW_SAPP_D_TIME]
	SELECT * INTO [Staging].[S_CDW_SAPP_D_TIME]
		FROM [Landing].[U_CDW_SAPP_D_TIME] WHERE 1=2;

	MERGE INTO [Staging].[S_CDW_SAPP_D_TIME] TRG
	USING [Landing].[U_CDW_SAPP_D_TIME] SRC ON 
	TRG.TIMEID = SRC.TIMEID

	WHEN NOT MATCHED 
	THEN INSERT (TIMEID, DAY, MONTH,QUARTER,YEAR, LOADING_DATE, SOURCE_DATA)
	VALUES (SRC.TIMEID, SRC.DAY,SRC.MONTH,SRC.QUARTER,SRC.YEAR, SRC.LOADING_DATE, SRC.SOURCE_DATA)

	WHEN MATCHED AND(
	TRG.TIMEID != SRC.TIMEID OR 
	TRG.DAY != SRC.DAY OR
	TRG.MONTH != SRC.MONTH OR
	TRG.QUARTER != SRC.QUARTER OR
	TRG.YEAR != SRC.YEAR OR
	TRG.LOADING_DATE != SRC.LOADING_DATE OR 
	TRG.SOURCE_DATA != SRC.SOURCE_DATA)
	THEN UPDATE SET 
	TRG.TIMEID = SRC.TIMEID, 
	TRG.DAY = SRC.DAY,
	TRG.MONTH = SRC.MONTH,
	TRG.QUARTER = SRC.QUARTER,
	TRG.YEAR = SRC.YEAR,
	TRG.LOADING_DATE = SRC.LOADING_DATE,  
	TRG.SOURCE_DATA = SRC.SOURCE_DATA;

---------------------------------------------------------PRODUCT STAGING------------------------------------------------------------------------
/*DROP TABLE [Staging].[S_CDW_SAPP_PRODUCT]
SELECT * FROM [Staging].[S_CDW_SAPP_PRODUCT]
SELECT * FROM [Landing].[U_CDW_SAPP_D_PRODUCT]*/

	DROP TABLE IF EXISTS [Staging].[S_CDW_SAPP_PRODUCT]
	SELECT * INTO [Staging].[S_CDW_SAPP_PRODUCT]
		FROM [Landing].[U_CDW_SAPP_D_PRODUCT] WHERE 1=2;

	MERGE INTO [Staging].[S_CDW_SAPP_PRODUCT] TRG
	USING [Landing].[U_CDW_SAPP_D_PRODUCT] SRC ON 
	TRG.PRODUCT_CODE= SRC.PRODUCT_CODE

	WHEN NOT MATCHED 
	THEN INSERT (PRODUCT_CODE, PRODUCT_NAME, SUPPLIER_ID, PRODUCT_PRICE, LOADING_DATE, SOURCE_DATA)
	VALUES (SRC.PRODUCT_CODE, SRC.PRODUCT_NAME, SRC.SUPPLIER_ID, SRC.PRODUCT_PRICE, SRC.LOADING_DATE, SRC.SOURCE_DATA)

	WHEN MATCHED AND(
	TRG.PRODUCT_CODE != SRC.PRODUCT_CODE OR 
	TRG.PRODUCT_NAME != SRC.PRODUCT_NAME OR
	TRG.SUPPLIER_ID != SRC.SUPPLIER_ID OR 
	TRG.PRODUCT_PRICE != SRC.PRODUCT_PRICE OR
	TRG.LOADING_DATE != SRC.LOADING_DATE OR
	TRG.SOURCE_DATA != SRC.SOURCE_DATA)
	THEN UPDATE SET 
	TRG.PRODUCT_CODE = SRC.PRODUCT_CODE,  
	TRG.PRODUCT_NAME = SRC.PRODUCT_NAME, 
	TRG.SUPPLIER_ID = SRC.SUPPLIER_ID,  
	TRG.PRODUCT_PRICE = SRC.PRODUCT_PRICE,
	TRG.LOADING_DATE = SRC.LOADING_DATE, 
	TRG.SOURCE_DATA = SRC.SOURCE_DATA;




